---
title: "SA app user data Latin America 1Dec20-1Jan22"
author: "Dani Behonick"
date: "2/2/2022"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
install.packages("readr")
install.packages("dplyr")
install.packages("ggplot2")
library(readr)
library(dplyr)
library(ggplot2)
```
*NEW USERS*
```{r}
LAnewusers_Dec20Jan22 <- read.csv("newusers_20201201to20220101.csv",
skip = 1, head = FALSE, sep = ",")
```

*Data cleaning*
```{r}
#columns renamed
colnames(LAnewusers_Dec20Jan22) <- c("Country_ID", "2021_01",
"2020_12", "2021_06", "2021_11", "2021_05", "2021_02", "2021_08",
"2021_12", "2021_07", "2021_10", "2021_09", "2021_04", "2021_03",
"2022_01", "Totals")

#header rows and data entries for non-Wyss LA countries removed
LAnewusers_Dec20Jan22 <- LAnewusers_Dec20Jan22 %>%
filter(Country_ID == "MX" | Country_ID == "AR" | Country_ID == "CO" |
Country_ID == "GT" | Country_ID == "HN" | Country_ID == "PE" |
Country_ID == "EC")

#transposed rows/columns
LAnewusers_Dec20Jan22_2 <- t(LAnewusers_Dec20Jan22[-1])
colnames(LAnewusers_Dec20Jan22_2) <- LAnewusers_Dec20Jan22[, 1]

#making time a recognized column variable
LAnewusers_Dec20Jan22_2 <- cbind(rownames(LAnewusers_Dec20Jan22_2), 
  LAnewusers_Dec20Jan22_2)
rownames(LAnewusers_Dec20Jan22_2) <- NULL

#Totals row removed
LAnewusers_Dec20Jan22_2 <- LAnewusers_Dec20Jan22_2[-c(15), ]

#make it a dataframe
LAnewusers_Dec20Jan22_2 <- as.data.frame(LAnewusers_Dec20Jan22_2)
```

```{r}
install.packages("tidyr")
library(tidyr)
```
```{r}
#pivot to make CountryID a callable variable
LAnewusers_Dec20Jan22_3 <- pivot_longer(LAnewusers_Dec20Jan22_2, cols=2:8, names_to = "Country", values_to = "New_users")

#rename columns
colnames(LAnewusers_Dec20Jan22_3) <- c("Year_Month","CountryID","New_Users")

#make it a dataframe
LAnewusers_Dec20Jan22_3 <- as.data.frame(LAnewusers_Dec20Jan22_3)
```

```{r}
#coerce New_Users to numeric variable rather than character
typeof(LAnewusers_Dec20Jan22_3$New_Users)
LAnewusers_Dec20Jan22_3$New_Users <- as.numeric(LAnewusers_Dec20Jan22_3$New_Users)
typeof(LAnewusers_Dec20Jan22_3$New_Users)

#make Month_Year a date/time object
install.packages("zoo")
library(zoo)
Year_Month <- LAnewusers_Dec20Jan22_3$Year_Month
Year_Month_2 <- as.yearmon(as.character(Year_Month), "%Y_%m")
LAnewusers_Dec20Jan22_3[ , 'Year_Month'] <- Year_Month_2
typeof(LAnewusers_Dec20Jan22_3$Year_Month)
```


```{r}
ggplot(data = LAnewusers_Dec20Jan22_3, aes(x=Year_Month, y=New_Users)) + 
  geom_line(aes(color=CountryID)) + labs(x = "Time", y = "New Users", 
  title = "Total new users, LA Wyss countries, 2020Dec-2022Jan") + 
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1))
```
*RETURN USERS*
```{r}
LAreturningusers_Dec20Jan22 <- read.csv("returningusers_20201201to20220101.csv",
skip = 1, head = FALSE, sep = ",")
```

*Data cleaning*
```{r}
#columns renamed
colnames(LAreturningusers_Dec20Jan22) <- c("Country_ID", "2021_01",
"2020_12", "2021_02", "2021_05", "2021_06", "2021_04", "2021_03",
"2021_12", "2021_10", "2021_07", "2021_11", "2021_09", "2022_01", "Totals")

#header rows and data entries for non-Wyss LA countries removed
LAreturningusers_Dec20Jan22 <- LAreturningusers_Dec20Jan22 %>%
filter(Country_ID == "MX" | Country_ID == "AR" | Country_ID == "CO" |
Country_ID == "GT" | Country_ID == "HN" | Country_ID == "PE" |
Country_ID == "EC")

#transposed rows/columns
LAreturningusers_Dec20Jan22_2 <- t(LAreturningusers_Dec20Jan22[-1])
colnames(LAreturningusers_Dec20Jan22_2) <- LAreturningusers_Dec20Jan22[, 1]

#making time a recognized column variable
LAreturningusers_Dec20Jan22_2 <- cbind(rownames(LAreturningusers_Dec20Jan22_2), 
  LAreturningusers_Dec20Jan22_2)
rownames(LAreturningusers_Dec20Jan22_2) <- NULL

#Totals row removed
LAreturningusers_Dec20Jan22_2 <- LAreturningusers_Dec20Jan22_2[-c(14), ]

#make it a dataframe
LAreturningusers_Dec20Jan22_2 <- as.data.frame(LAreturningusers_Dec20Jan22_2)

#pivot to make CountryID a callable variable
LAreturningusers_Dec20Jan22_3 <- pivot_longer(LAreturningusers_Dec20Jan22_2, cols=2:8, names_to = "Country", values_to = "New_users")

#rename columns
colnames(LAreturningusers_Dec20Jan22_3) <- c("Year_Month","CountryID","New_Users")

#make it a dataframe
LAreturningusers_Dec20Jan22_3 <- as.data.frame(LAreturningusers_Dec20Jan22_3)

#rename columns
colnames(LAreturningusers_Dec20Jan22_3) <- c("Year_Month","CountryID","New_Users")

#make it a dataframe
LAreturningusers_Dec20Jan22_3 <- as.data.frame(LAreturningusers_Dec20Jan22_3)

#coerce New_Users to numeric variable rather than character
LAreturningusers_Dec20Jan22_3$New_Users <- as.numeric(LAreturningusers_Dec20Jan22_3$New_Users)
typeof(LAreturningusers_Dec20Jan22_3$New_Users)

#make Month_Year a date/time object
Year_Month_returning <- LAreturningusers_Dec20Jan22_3$Year_Month
Year_Month_returning_2 <- as.yearmon(as.character(Year_Month_returning), "%Y_%m")
LAreturningusers_Dec20Jan22_3[ , 'Year_Month'] <- Year_Month_returning_2
typeof(LAreturningusers_Dec20Jan22_3$Year_Month)

ggplot(data = LAreturningusers_Dec20Jan22_3, aes(x=Year_Month, y=New_Users)) + 
  geom_line(aes(color=CountryID)) + labs(x = "Year_Month", y = "New Users", 
  title = "Total returning users, LA Wyss countries, 2020Dec-2022Jan") + 
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1))
```



